services:
  web:
    image: leodbrs/projetdevops
    ports:
      - "80:80"
    depends_on:
      - database
    volumes:
      - ./web/dvdrental.conf:/etc/apache2/sites-available/dvdrental.conf
      - ./data/app:/var/www/dvdrental/app
  database:
    image: postgres:bullseye
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  reverse-proxy:
    image: traefik
    ports:
      - "80:80"
      # - "443:443"
      - "5432:5432"
      - "8080:8080"
    volumes:
      - ./reverse-proxy/traefik.yml:/etc/traefik/traefik.yml
