services:

  reverse-proxy:
    image: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
      # - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # volumes:
      #   - ./reverse-proxy/traefik.yml:/etc/traefik/traefik.yml

  web:
    image: leodbrs/projetdevops
    depends_on:
      - database
      - reverse-proxy
    deploy:
      replicas: 10
    volumes:
      - ./web/dvdrental.conf:/etc/apache2/sites-available/dvdrental.conf
      - ./data/app:/var/www/dvdrental/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.entrypoints=web"

  database:
    image: postgres:bullseye
    deploy:
      replicas: 5
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
