# Define node properties
nodes = [
  {
    :hostname => "manager",
    :ram => 2048,
    :cpu => 2,
    :ip => "192.168.56.11"
  },
  {
    :hostname => "worker-01",
    :ram => 1024,
    :cpu => 1,
    :ip => "192.168.56.21"
  },
  {
    :hostname => "worker-02",
    :ram => 1024,
    :cpu => 2,
    :ip => "192.168.56.22"
  }
]
n = 0

Vagrant.configure("2") do |config|
  # Start the nodes
  nodes.each do |nodes|
    config.vm.define nodes[:hostname] do |node|
      node.vm.box = "debian/buster64"
      node.vm.hostname = nodes[:hostname]
      node.vm.network "private_network", ip:nodes[:ip]
      node.vbguest.auto_update = false
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = nodes[:ram]
        vb.cpus = nodes[:cpu]
      end
      n = n + 1
    end
  end

  # Provision the nodes with Ansible
  if n == 2
    config.vm.provision "ansible", after: :all do |ansible|
      ansible.host_vars = { "manager" => { "swarm_host" => nodes[0][:ip] } }
      ansible.groups = { "workers" => ["worker-01", "worker-02"] }
      ansible.playbook = "../Ansible/setup-cluster.yml"
      ansible.limit = "all"
    end
end