machines=[
  {
    :hostname => "manager",
    :box => "mathisc/infradevops",
    :ram => 2048,
    :cpu => 2,
    :ip => "192.168.56.11"
  },
  {
    :hostname => "worker-01",
    :box => "mathisc/infradevops",
    :ram => 1024,
    :cpu => 1,
    :ip => "192.168.56.21"
  },
  {
    :hostname => "worker-02",
    :box => "mathisc/infradevops",
    :ram => 1024,
    :cpu => 2,
    :ip => "192.168.56.22"
  }
]
Vagrant.configure("2") do |config|
  machines.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip:machine[:ip]
      node.vbguest.auto_update = false
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]
      end
    end
  end 
end