---
- name: Install required system packages
  apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
  loop: ["ca-certificates", "curl", "gnupg", "lsb-release", "git", "nfs-common"]

- name: Add Docker GPG apt Key
  apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

- name: Add Docker Repository
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
      state: present
      update_cache: yes

- name: Update apt and install docker-ce
  apt:
      name: docker-ce
      update_cache: yes
      state: latest

- name: Add user vagrant to the docker group
  user:
      name: vagrant
      groups: docker
      append: yes

- name: Install docker-compose
  remote_user: ubuntu
  get_url:
      url: https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: "+x"
