---
- name: Check if Swarm has already been Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

- name: Initialize a cluster
  shell: >
      docker swarm init
      --advertise-addr={{ hostvars[inventory_hostname]['swarm_host'] }}:2377
  when: swarm_status.rc != 0
  run_once: true

- name: Get the worker join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token
