---
- name: Create a network for traefik
  shell: >
      docker network create --driver=overlay traefik-public

# - name: Deploy a service to the Cluster
#   shell: >
#       docker stack deploy --compose-file /production/InfraDevOps/Docker/docker-compose.yml infradevops

- name: Deploy a visualizer container for Oral présentation
  shell: >
      docker run -it -d -p 8082:8080 -v /var/run/docker.sock:/var/run/docker.sock dockersamples/visualizer