---
- name: Create a network for traefik
  shell: >
      docker network create --driver=overlay traefik-public

- name: Deploy a service to the Cluster
  shell: >
      docker stack deploy --compose-file /production/InfraDevOps/Docker/docker-compose.yml infradevops
