---
# This playbook deploys the swarm cluster

- name: Apply common configuration to all nodes
  hosts: all
  become: true
  strategy: free
  roles:
      - common

- name: Initialize the cluster on the manager
  hosts: manager
  become: true
  roles:
      - master

- name: Make workers join the cluster
  hosts: workers
  become: true
  roles:
      - workers
