---
- name: Add Workers to the Swarm
  shell: >
      docker swarm join
      --token {{ hostvars[inventory_hostname]['manager']['worker_token']['stdout'] }}
      {{ hostvars[inventory_hostname]['swarm_host'] }}:2377
