---
- name: Add Workers to the Swarm
  shell: >
      docker swarm join --token {{ hostvars['manager']['worker_token']['stdout'] }} {{ hostvars['manager']['swarm_host'] }}:2377
  ignore_errors: true

- name: Create mountable dir
  file: path=/data/dvdrental state=directory mode=777 owner=root group=root

- name: Set mountpoints
  mount:
      name: /data/dvdrental
      src: "{{ hostvars['manager']['swarm_host'] }}:/data/dvdrental"
      state: mounted
      fstype: nfs
