---
- name: Check if Swarm has already been Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

- name: Initialize a cluster
  shell: >
      docker swarm init
      --advertise-addr={{ hostvars[inventory_hostname]['swarm_host'] }}:2377
  when: swarm_status.rc != 0
  run_once: true

- name: Get the worker join-token
  shell: docker swarm join-token worker --quiet
  register: worker_token

- name: Download Cluster GitHub repository
  git: >
      repo=https://leodbrs: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@github.com/leodbrs/InfraDevOps.git
      dest=/production/

- name: Download WebApp GitHub repository
  git: >
      repo=https://leodbrs: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@github.com/leodbrs/DVD-Rental.git
      dest=/tmp/DVD-Rental/

- name: Moving WebApp folder
  copy:
      remote_src: true
      src: /tmp/DVD-Rental/app
      dest: /data/dvdrental/

- name: Removing WebApp GitHub repository
  file:
      path: /tmp/DVD-Rental/
      state: absent

- name: Install nfs-kernel-server packages
  apt:
      name: nfs-kernel-server
      state: latest
      update_cache: yes

- name: Copy /etc/exports
  template: src=exports.j2 dest=/etc/exports owner=root group=root

- name: Restart nfs server
  service: name=nfs-kernel-server state=restarted
